name: Auto merge after checks pass

on:
  check_suite:
    types: [completed]

jobs:
  automerge:
    if: github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Merge the pull request
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.check_suite.pull_requests[0].number }}
          merge-method: squash